### PR TITLE
fix: best to check the values and make sure there's some

### LINKED ISSUE #1047: Advanced filter not loading
When I try to add Advanced filter to an integration there's just infinite loading spinner with the following browser console exception.

@gashcrumb is it related to Basic filter fix actually, because Advanced filter was working yesterday for me.

```
vendor.1aef838c4a5fa5657cd0.bundle.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at t.loadFormSetup (/2.3d08ad3091edc782fca0.chunk.js:1)
    at /2.3d08ad3091edc782fca0.chunk.js:1
    at t.invoke (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at Object.onInvoke (vendor.1aef838c4a5fa5657cd0.bundle.js:1)
    at t.invoke (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at n.run (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at polyfills.2c1aa39973715b94b1ea.bundle.js:1
    at t.invokeTask (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at Object.onInvokeTask (vendor.1aef838c4a5fa5657cd0.bundle.js:1)
    at t.invokeTask (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at n.runTask (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at u (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at XMLHttpRequest.invoke (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at Function.keys (<anonymous>)
    at t.loadFormSetup (/2.3d08ad3091edc782fca0.chunk.js:1)
    at /2.3d08ad3091edc782fca0.chunk.js:1
    at t.invoke (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at Object.onInvoke (vendor.1aef838c4a5fa5657cd0.bundle.js:1)
    at t.invoke (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at n.run (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at polyfills.2c1aa39973715b94b1ea.bundle.js:1
    at t.invokeTask (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at Object.onInvokeTask (vendor.1aef838c4a5fa5657cd0.bundle.js:1)
    at t.invokeTask (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at n.runTask (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at u (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at XMLHttpRequest.invoke (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at new g (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at l (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at polyfills.2c1aa39973715b94b1ea.bundle.js:1
    at t.invokeTask (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at Object.onInvokeTask (vendor.1aef838c4a5fa5657cd0.bundle.js:1)
    at t.invokeTask (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at n.runTask (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at u (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
    at XMLHttpRequest.invoke (polyfills.2c1aa39973715b94b1ea.bundle.js:1)
```

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #1047 

Also gets rid of `Object.keys()` to make @kahboom happy :-)

@dsimansk FYI

### CODE REVIEW

File: app/ui/src/app/integrations/edit-page/step-configure/step-configure.component.ts [hunk 1]
```diff
@@ -224,12 +224,14 @@ export class IntegrationsStepConfigureComponent extends FlowPage implements OnIn
       category
     );
     */
-    // supress null values
-    Object.keys(values).forEach(key => {
-      if (values[key] === 'null') {
-        values[key] = undefined;
+    if (values) {
+      // supress null values
```
Comment (deeleman) [inline app/ui/src/app/integrations/edit-page/step-configure/step-configure.component.ts]: I think the intent is pretty obvious and we don't need a comment to clarify it LOL :D 

BTW, do you want to assign the `undefined` value to these fields or just remove those from the `values` object (provided they've been flagged as optional in its TypeScript interface)? If you strive to do the latter, I'd suggest to [take a look into this](https://github.com/syndesisio/syndesis/blob/7e4370a6c3af492054771ce88c80ad67c63dbfc9/app/ui/src/app/customizations/api-connector/api-connector.service.ts#L80-L94).

In the example provided within our codebase the _for/in_ loop is constrained to remove only the empty/null/undefined properties found in the object definition that belong to its type, not including those which are inherited though. 

Aside from the comment and this word of caution, it LGTM

Comment (gashcrumb) [reply app/ui/src/app/integrations/edit-page/step-configure/step-configure.component.ts]: Yeah, so this apparently came about as a side effect of the backend setting values to null for empty strings.  I considered actually putting this right into the form service, though it does bug me that basically then you can never have a value in a `configuredProperties` map set to the string `null` :-)

I'm fine with setting it to just `undefined`, when the form service builds the form the resulting value will either be unset or whatever the default value is set to in the properties object.

**Comment by gashcrumb** [comment]
@syndesisio/ui-api can someone review this so it can get into tp3?
