### PR TITLE
Nicer error handling when fetching dynamic metadata

### LINKED ISSUE #1659: When exceeded salesforce API call limit, connection message "unexpected HTTP error"
There is this message, when I exceeded salesforce API calls limit: "An unexpected HTTP error occured. Please check stack strace".
I want to ask, whether there could be a better way to notify the user, that he exceeded the salesforce API call limit, because looking into stack trace (there is a typo at least) is quite cumbersome.

The screenshots:

salesforce_api_calls_exceeded
an_unexpected_salesforce_error

### PR DESCRIPTION
**Pull request by zregvart**
There is much more details in the commit messages.

In nutshell this adds hystrix when invoking the `syndesis-meta` for dynamic metadata. This way we can guarantee if an error or no response within 1.5s is  received from `syndesis-meta` that it can be properly handled.

The handling part uses a new mixin for the API responses, by which we can add `_meta` property to any API response. This `_meta` property consists (currently) of only two properties (type & message).

Adds an interceptor for HTTP responses in the UI, that checks if the `_meta` property is present in the response and displays a toast notification with the provided content.

Fixes #1659

### CODE REVIEW

**Comment by gashcrumb** [comment]
So I'm guess here that really we don't want to keep this interceptor but instead handle the response properly from wherever a given request originates in the code, right?

**Comment by zregvart** [comment]
> So I'm guess here that really we don't want to keep this interceptor but instead handle the response properly from wherever a given request originates in the code, right?

That depends, the way it's proposed the server might or might not add that `_meta` property, and the it will be returned in addition to the usual response (mixed in). This allows other use cases, in fact this is very similar pattern to the `flash` scope usually used in webapps. To me it makes sense to handle this at the single point.

**Comment by gashcrumb** [comment]
That seems a bit decoupled though from the actual page that's potentially going to hit a problem, doesn't it?  I guess I don't understand how this addresses the error that's displayed in #1659 exactly, as I suspect now the behavior will be that we still see that error but also now we'll get a notification in addition to that error with more information, right?

Not that I'm against having this, though as a kind of global interceptor I do have concerns that this could cause a notification storm, etc :-)

**Comment by gashcrumb** [comment]
Ah, k, thanks for the details!  I think it should be fine then.

I suspect that really we're talking about client initiated requests, so if
there's a flood of alerts we're doing it wrong anyways ;-)

File: app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/MetadataCommand.java [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+import com.netflix.hystrix.HystrixCommand;
+import com.netflix.hystrix.HystrixCommandGroupKey;
+import com.netflix.hystrix.HystrixCommandProperties;
+import com.netflix.hystrix.HystrixThreadPoolProperties;
+
+class MetadataCommand extends HystrixCommand<DynamicActionMetadata> {
+
+    private static final int THREAD_COUNT = 3;
+
+    private static final int TIMEOUT = 1500;
```
Comment (lburgazzoli) [inline app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/MetadataCommand.java]: Not a big issue but wondering if we can make those values configurable

**Comment by zregvart** [comment]
@lburgazzoli I've added the ability to configure thread pool size and timeout, do you think this can be merged now?
