### PR TITLE
Fixed AMQ connection verification

### LINKED ISSUE #466: Fix ActiveMQ Connection validation
Validate button is missing for ActiveMQ Connection, despite an ActiveMQ verifier implementation.

### LINKED ISSUE #622: ActiveMQ connection verifier doesn't honour provided values
Regardless of provided values for Connection, the validation is always successful.

screen shot 2017-12-06 at 09 48 05

Verifier log:
```
2017-12-06 08:49:24.410  WARN 1 --- [ XNIO-2 task-22] o.apache.activemq.broker.BrokerService   : Memory Usage for the Broker (1024mb) is more than the maximum available for the JVM: 228 mb - resetting to 70% of maximum available: 159 mb
2017-12-06 08:49:24.415  INFO 1 --- [ XNIO-2 task-22] o.apache.activemq.broker.BrokerService   : Using Persistence Adapter: MemoryPersistenceAdapter
2017-12-06 08:49:24.415  INFO 1 --- [ XNIO-2 task-22] o.apache.activemq.broker.BrokerService   : Apache ActiveMQ 5.15.2 (localhost, ID:syndesis-verifier-1-9hgqn-40167-1512545194998-0:498) is starting
2017-12-06 08:49:24.416  INFO 1 --- [  JMX connector] o.a.a.broker.jmx.ManagementContext       : JMX consoles can connect to service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi
2017-12-06 08:49:24.416  INFO 1 --- [ XNIO-2 task-22] o.apache.activemq.broker.BrokerService   : Apache ActiveMQ 5.15.2 (localhost, ID:syndesis-verifier-1-9hgqn-40167-1512545194998-0:498) started
2017-12-06 08:49:24.416  WARN 1 --- [ XNIO-2 task-22] o.apache.activemq.broker.BrokerService   : Temporary Store limit is 51200 mb (current store usage is 0 mb). The data directory: /deployments only has 2590 mb of usable space. - resetting to maximum available disk space: 2590 mb
2017-12-06 08:49:24.417  INFO 1 --- [ XNIO-2 task-22] o.a.activemq.broker.TransportConnector   : Connector vm://localhost started
2017-12-06 08:49:24.426  INFO 1 --- [ XNIO-2 task-22] o.a.activemq.broker.TransportConnector   : Connector vm://localhost stopped
2017-12-06 08:49:24.426  INFO 1 --- [ XNIO-2 task-22] o.apache.activemq.broker.BrokerService   : Apache ActiveMQ 5.15.2 (localhost, ID:syndesis-verifier-1-9hgqn-40167-1512545194998-0:498) is shutting down
2017-12-06 08:49:24.427  INFO 1 --- [ XNIO-2 task-22] o.apache.activemq.broker.BrokerService   : Apache ActiveMQ 5.15.2 (localhost, ID:syndesis-verifier-1-9hgqn-40167-1512545194998-0:498) uptime 0.017 seconds
2017-12-06 08:49:24.427  INFO 1 --- [ XNIO-2 task-22] o.apache.activemq.broker.BrokerService   : Apache ActiveMQ 5.15.2 (localhost, ID:syndesis-verifier-1-9hgqn-40167-1512545194998-0:498) is shutdown
```

### PR DESCRIPTION
**Pull request by dhirajsb**
This fixes #622, fixes #466

### CODE REVIEW

File: app/connectors/connectors/jms/activemq-connectors/activemq-model/src/main/java/io/syndesis/connector/jms/ActiveMQConnectorVerifierExtension.java [hunk 1]
```diff
@@ -85,6 +86,14 @@ private void verifyCredentials(ResultBuilder builder, Map<String, Object> parame
                     .parameterKey("username")
                     .parameterKey("password")
                     .build());
+        } finally {
+            if (connection != null) {
+                try {
+                    connection.close();
```
Comment (zregvart) [inline app/connectors/connectors/jms/activemq-connectors/activemq-model/src/main/java/io/syndesis/connector/jms/ActiveMQConnectorVerifierExtension.java]: Perhaps we could use try-with-resources here

Comment (dhirajsb) [reply app/connectors/connectors/jms/activemq-connectors/activemq-model/src/main/java/io/syndesis/connector/jms/ActiveMQConnectorVerifierExtension.java]: Connection is not a Closable.
